services:

  backend:
    build: .
    container_name: products_manager
    expose:
      - "8080:8080"  # Mapea el puerto 80 del contenedor al puerto 8080 del host
    networks:
      - backend  

  nginx:
    image: nginx:latest
    container_name: server_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - backend

networks:
  backend:
    driver: bridge